[project]
name = "study2work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Đào Văn Hùng", email = "daohungmt2005@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
study2work = "study2work:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "apps/ai-server",
]
