-- Study2Work / Work server database schema for Neon PostgreSQL
-- Source: apps/work-server/docs/database/schema.sql
-- This script runs against the Neon database selected by the connection.
-- It intentionally does not CREATE DATABASE, USE, or DROP tables. It only
-- backfills the mobile bannganh lookup from existing Neon values.

SET search_path TO public;
SET TIME ZONE 'UTC';

CREATE TABLE "SinhVien" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "hoten" VARCHAR(50),
    "email" VARCHAR(50),
    "matkhau" VARCHAR(20),
    "chuyennganh" VARCHAR(50),
    "avt" VARCHAR(191),

    CONSTRAINT "SinhVien_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "DoanhNghiep" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "hoten" VARCHAR(50),
    "email" VARCHAR(50),
    "matkhau" VARCHAR(50),
    "diachi" VARCHAR(100),
    "sodienthoai" VARCHAR(20),
    "avt" VARCHAR(191),

    CONSTRAINT "DoanhNghiep_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Chat" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "sinhvien_id" BIGINT,
    "doanhnghiep_id" BIGINT,
    "nguoigui" VARCHAR(191),
    "nguoinhan" VARCHAR(191),
    "noidung" VARCHAR(191),
    "ngaygui" TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP(3),
    "trangthai" BOOLEAN,

    CONSTRAINT "Chat_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Cv" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "avt" VARCHAR(191),
    "hoten" VARCHAR(191) NOT NULL,
    "ngaysinh" TIMESTAMPTZ(3),
    "gioitinh" VARCHAR(191),
    "email" VARCHAR(191) NOT NULL,
    "sdt" VARCHAR(191),
    "diachi" VARCHAR(191),
    "vitri" VARCHAR(191),
    "nganh" VARCHAR(191),
    "muctieunghiep" VARCHAR(191),
    "hocvan" VARCHAR(191),
    "kinhnghiem" VARCHAR(191),
    "kynang" VARCHAR(191),
    "ngoaingu" VARCHAR(191),
    "chungchi" VARCHAR(191),
    "duan" VARCHAR(191),
    "giaithuong" VARCHAR(191),
    "hoatdong" VARCHAR(191),
    "social" JSONB,
    "portfolio" VARCHAR(191),
    "luongmongmuon" VARCHAR(191),
    "created_at" TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP(3),
    "sinhvien_id" BIGINT,

    CONSTRAINT "Cv_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "DoanChat" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "sinhvien_id" BIGINT NOT NULL,
    "doanhnghiep_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP(3),

    CONSTRAINT "DoanChat_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "JD" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ten_vi_tri" VARCHAR(191) NOT NULL,
    "phong_ban" VARCHAR(191),
    "cap_bac" VARCHAR(191),
    "bao_cao_cho" VARCHAR(191),
    "nhiem_vu" VARCHAR(191),
    "trinh_do" VARCHAR(191),
    "kinh_nghiem" VARCHAR(191),
    "ky_nang" VARCHAR(191),
    "ky_nang_mem" VARCHAR(191),
    "uu_tien" VARCHAR(191),
    "muc_luong" VARCHAR(191),
    "phuc_loi" VARCHAR(191),
    "moi_truong" VARCHAR(191),
    "dia_diem" VARCHAR(191),
    "thoi_gian" VARCHAR(191),
    "han_nop" VARCHAR(191),
    "cach_ung_tuyen" VARCHAR(191),
    "ngay_tao" TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP(3),
    "mo_ta" VARCHAR(191),
    "doanhnghiep_id" BIGINT,
    "ten_cong_ty" VARCHAR(191),
    "nganh" VARCHAR(191),
    "avt" VARCHAR(191),

    CONSTRAINT "JD_pkey" PRIMARY KEY ("id")
);

-- Lookup used by both mobile apps. The table name is intentionally lowercase
-- because the mobile SQL queries use the PostgreSQL unquoted name bannganh.
CREATE TABLE bannganh (
    "nganh" VARCHAR(191) NOT NULL,
    CONSTRAINT bannganh_pkey PRIMARY KEY ("nganh")
);

-- Backfill the lookup from values already present in the Neon database. This
-- is idempotent and also provides a safe fallback when the retired Supabase
-- project cannot be exported anymore.
INSERT INTO bannganh ("nganh")
SELECT DISTINCT btrim(value)
FROM (
    SELECT "nganh" AS value FROM "JD"
    UNION
    SELECT "chuyennganh" AS value FROM "SinhVien"
) AS source_values
WHERE value IS NOT NULL AND btrim(value) <> ''
ON CONFLICT ("nganh") DO NOTHING;

CREATE TABLE "ThongBaoDN" (
    "id_dn" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ten_dn" VARCHAR(191),
    "email" VARCHAR(191),
    "mat_khau" VARCHAR(191),
    "sdt" VARCHAR(191),
    "logo" VARCHAR(191),
    "trang_thai" VARCHAR(191),
    "ngay_tao" VARCHAR(191),
    "doanhnghiep_id" BIGINT,

    CONSTRAINT "ThongBaoDN_pkey" PRIMARY KEY ("id_dn")
);

CREATE TABLE "ThongBaoSV" (
    "id_sv" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ho_ten" VARCHAR(191),
    "email" VARCHAR(191),
    "mat_khau" VARCHAR(191),
    "sdt" VARCHAR(191),
    "avt_sv" VARCHAR(191),
    "trang_thai" VARCHAR(191),
    "ngay_tao" VARCHAR(191),
    "sinhvien_id" BIGINT,

    CONSTRAINT "ThongBaoSV_pkey" PRIMARY KEY ("id_sv")
);

CREATE TABLE "TopJD" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    "jd_id" BIGINT,

    CONSTRAINT "TopJD_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "TopCV" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    CONSTRAINT "TopCV_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "UngVien" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    "sinhvien_id" BIGINT,
    "doanhnghiep_id" BIGINT,
    "trangthai" VARCHAR(191) DEFAULT 'chưa ứng tuyển',
    "jd_id" BIGINT,

    CONSTRAINT "UngVien_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "DoanhNghiep_email_key"
    ON "DoanhNghiep" ("email");

CREATE UNIQUE INDEX "SinhVien_email_key"
    ON "SinhVien" ("email");

CREATE UNIQUE INDEX "Cv_sinhvien_id_key"
    ON "Cv" ("sinhvien_id");

CREATE UNIQUE INDEX "UngVien_jd_sinhvien_key"
    ON "UngVien" ("jd_id", "sinhvien_id");

ALTER TABLE "Chat"
    ADD CONSTRAINT "Chat_sinhvien_id_fkey"
    FOREIGN KEY ("sinhvien_id") REFERENCES "SinhVien" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Chat"
    ADD CONSTRAINT "Chat_doanhnghiep_id_fkey"
    FOREIGN KEY ("doanhnghiep_id") REFERENCES "DoanhNghiep" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Cv"
    ADD CONSTRAINT "Cv_sinhvien_id_fkey"
    FOREIGN KEY ("sinhvien_id") REFERENCES "SinhVien" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "DoanChat"
    ADD CONSTRAINT "DoanChat_sinhvien_id_fkey"
    FOREIGN KEY ("sinhvien_id") REFERENCES "SinhVien" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "DoanChat"
    ADD CONSTRAINT "DoanChat_doanhnghiep_id_fkey"
    FOREIGN KEY ("doanhnghiep_id") REFERENCES "DoanhNghiep" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "JD"
    ADD CONSTRAINT "JD_doanhnghiep_id_fkey"
    FOREIGN KEY ("doanhnghiep_id") REFERENCES "DoanhNghiep" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "ThongBaoDN"
    ADD CONSTRAINT "ThongBaoDN_doanhnghiep_id_fkey"
    FOREIGN KEY ("doanhnghiep_id") REFERENCES "DoanhNghiep" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "ThongBaoSV"
    ADD CONSTRAINT "ThongBaoSV_sinhvien_id_fkey"
    FOREIGN KEY ("sinhvien_id") REFERENCES "SinhVien" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "TopJD"
    ADD CONSTRAINT "TopJD_jd_id_fkey"
    FOREIGN KEY ("jd_id") REFERENCES "JD" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "UngVien"
    ADD CONSTRAINT "UngVien_sinhvien_id_fkey"
    FOREIGN KEY ("sinhvien_id") REFERENCES "SinhVien" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "UngVien"
    ADD CONSTRAINT "UngVien_doanhnghiep_id_fkey"
    FOREIGN KEY ("doanhnghiep_id") REFERENCES "DoanhNghiep" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "UngVien"
    ADD CONSTRAINT "UngVien_jd_id_fkey"
    FOREIGN KEY ("jd_id") REFERENCES "JD" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE;
