-- Generated from 03_THIET_KE_CO_SO_DU_LIEU.md
-- Target database: identity_db
-- PostgreSQL V1-PILOT baseline DDL.
-- UUID v7 values are generated by the application; no UUID extension is required.
-- Cross-database foreign keys are intentionally absent.

SET client_min_messages = warning;
SET timezone = 'UTC';

DO $$
BEGIN
    CREATE TYPE account_status AS ENUM ('PENDING_EMAIL_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DELETION_PENDING', 'ANONYMIZED');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE audit_outcome AS ENUM ('SUCCESS', 'DENIED', 'FAILURE');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE mfa_method_type AS ENUM ('TOTP', 'RECOVERY_CODE');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE outbox_status AS ENUM ('PENDING', 'PUBLISHED', 'FAILED', 'DEAD_LETTER');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE session_status AS ENUM ('ACTIVE', 'REVOKED', 'COMPROMISED', 'EXPIRED');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE token_status AS ENUM ('ACTIVE', 'CONSUMED', 'REVOKED', 'EXPIRED');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE OR REPLACE FUNCTION s2w_touch_entity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    NEW.row_version := OLD.row_version + 1;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION s2w_prevent_update_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'table % is append-only', TG_TABLE_NAME USING ERRCODE = '55000';
END;
$$;

CREATE OR REPLACE FUNCTION s2w_prevent_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'table % does not allow hard delete', TG_TABLE_NAME USING ERRCODE = '55000';
END;
$$;

-- TBL-IAM-001 — users (source lines 101-108)
-- SPEC: Tập cột: `ENTITY`.
-- SPEC: Cột riêng: `status account_status NOT NULL DEFAULT 'PENDING_EMAIL_VERIFICATION'`; `display_name varchar(120) NULL`; `locale varchar(10) NOT NULL DEFAULT 'vi-VN'`; `timezone varchar(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh'`; `email_verified_at timestamptz NULL`; `suspended_at timestamptz NULL`; `suspension_reason varchar(500) NULL`; `deletion_requested_at timestamptz NULL`; `anonymized_at timestamptz NULL`; `privileged_mfa_required boolean NOT NULL DEFAULT false`.
-- SPEC: Ràng buộc: trạng thái `SUSPENDED` yêu cầu `suspended_at` và lý do; `ANONYMIZED` yêu cầu `anonymized_at`; tên hiển thị sau khi cắt khoảng trắng dài 1–120 nếu có giá trị.
-- SPEC: Chỉ mục: `(status, created_at DESC)`; chỉ mục một phần trên `(deletion_requested_at)` khi có giá trị.
-- SPEC: Dữ liệu: PII; giữ bản ghi định danh đã giả danh hóa vô thời hạn để bảo toàn khóa ngoại/kiểm toán.
CREATE TABLE IF NOT EXISTS users (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    row_version bigint NOT NULL DEFAULT 1,
    status account_status NOT NULL DEFAULT 'PENDING_EMAIL_VERIFICATION',
    display_name varchar(120) NULL,
    locale varchar(10) NOT NULL DEFAULT 'vi-VN',
    timezone varchar(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    email_verified_at timestamptz NULL,
    suspended_at timestamptz NULL,
    suspension_reason varchar(500) NULL,
    deletion_requested_at timestamptz NULL,
    anonymized_at timestamptz NULL,
    privileged_mfa_required boolean NOT NULL DEFAULT false,
    CONSTRAINT ck_users_row_version CHECK (row_version >= 1)
);

-- TBL-IAM-002 — user_emails (source lines 109-116)
-- SPEC: Tập cột: `ENTITY`.
-- SPEC: Cột riêng: `user_id uuid NOT NULL` FK `users.id`; `email_ciphertext bytea NOT NULL`; `email_normalized varchar(320) NOT NULL`; `is_primary boolean NOT NULL DEFAULT true`; `verified_at timestamptz NULL`; `replaced_at timestamptz NULL`.
-- SPEC: Ràng buộc: duy nhất toàn cục `email_normalized` khi `replaced_at IS NULL`; duy nhất một phần trên `(user_id)` khi `is_primary=true AND replaced_at IS NULL`; thư điện tử chuẩn phải khớp giá trị sau giải mã tại ranh giới ghi dữ liệu.
-- SPEC: Chỉ mục: `(user_id, replaced_at)`.
-- SPEC: Dữ liệu: PII; khi ẩn danh hóa, thay dữ liệu mã hóa và dữ liệu chuẩn hóa bằng bí danh không thể đảo ngược.
CREATE TABLE IF NOT EXISTS user_emails (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    row_version bigint NOT NULL DEFAULT 1,
    user_id uuid NOT NULL,
    email_ciphertext bytea NOT NULL,
    email_normalized varchar(320) NOT NULL,
    is_primary boolean NOT NULL DEFAULT true,
    verified_at timestamptz NULL,
    replaced_at timestamptz NULL,
    CONSTRAINT ck_user_emails_row_version CHECK (row_version >= 1)
);

-- TBL-IAM-003 — password_credentials (source lines 117-124)
-- SPEC: Tập cột: `ENTITY`.
-- SPEC: Cột riêng: `user_id uuid NOT NULL UNIQUE` FK `users.id`; `password_hash varchar(512) NOT NULL`; `algorithm varchar(32) NOT NULL DEFAULT 'ARGON2ID'`; `parameters jsonb NOT NULL`; `changed_at timestamptz NOT NULL`; `must_change boolean NOT NULL DEFAULT false`; `failed_count integer NOT NULL DEFAULT 0`; `locked_until timestamptz NULL`.
-- SPEC: Ràng buộc: `failed_count >= 0`; `algorithm='ARGON2ID'`; JSON chỉ chứa bộ nhớ/thời gian/song song/phiên bản, không chứa mật khẩu.
-- SPEC: Chỉ mục: duy nhất `user_id`; không lập chỉ mục hàm băm.
-- SPEC: Dữ liệu: SENSITIVE; không xóa mềm, việc đổi mật khẩu ghi vào nhật ký kiểm toán bảo mật.
CREATE TABLE IF NOT EXISTS password_credentials (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    row_version bigint NOT NULL DEFAULT 1,
    user_id uuid NOT NULL UNIQUE,
    password_hash varchar(512) NOT NULL,
    algorithm varchar(32) NOT NULL DEFAULT 'ARGON2ID',
    parameters jsonb NOT NULL,
    changed_at timestamptz NOT NULL,
    must_change boolean NOT NULL DEFAULT false,
    failed_count integer NOT NULL DEFAULT 0,
    locked_until timestamptz NULL,
    CONSTRAINT ck_password_credentials_row_version CHECK (row_version >= 1),
    CONSTRAINT ck_password_credentials_c86ee131 CHECK (failed_count >= 0),
    CONSTRAINT ck_password_credentials_952f85cc CHECK (algorithm='ARGON2ID')
);

-- TBL-IAM-004 — email_verification_tokens (source lines 125-133)
-- SPEC: Tập cột: `IMMUTABLE`.
-- SPEC: Cột riêng: `user_id uuid NOT NULL` FK `users.id`; `email_id uuid NOT NULL` FK `user_emails.id`; `purpose varchar(24) NOT NULL`; `token_hash char(64) NOT NULL UNIQUE`; `status token_status NOT NULL DEFAULT 'ACTIVE'`; `expires_at timestamptz NOT NULL`; `consumed_at timestamptz NULL`; `revoked_at timestamptz NULL`; `request_ip_hash char(64) NULL`.
-- SPEC: Ràng buộc: `expires_at>created_at`; dấu thời gian `consumed`/`revoked` phải phù hợp `status`. Việc đổi trạng thái do thủ tục có quyền bảo mật riêng thực hiện; về mặt quy tắc, bản ghi chỉ được thêm mới ngoài chuyển trạng thái một chiều.
-- SPEC: `purpose` chỉ nhận `REGISTER|CHANGE_EMAIL`; đổi thư điện tử chỉ nâng `user_emails.is_primary` sau khi xác minh và thu hồi địa chỉ thư điện tử chính cũ trong cùng giao dịch.
-- SPEC: Chỉ mục: `(user_id,status,expires_at DESC)`.
-- SPEC: Dữ liệu: SENSITIVE; dọn tải tin của mã thông báo sau 180 ngày, vẫn giữ kiểm toán.
CREATE TABLE IF NOT EXISTS email_verification_tokens (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    email_id uuid NOT NULL,
    purpose varchar(24) NOT NULL,
    token_hash char(64) NOT NULL UNIQUE,
    status token_status NOT NULL DEFAULT 'ACTIVE',
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz NULL,
    revoked_at timestamptz NULL,
    request_ip_hash char(64) NULL,
    CONSTRAINT ck_email_verification_tokens_e4dc85c8 CHECK (expires_at>created_at)
);

-- TBL-IAM-005 — password_reset_tokens (source lines 134-141)
-- SPEC: Tập cột: `IMMUTABLE`.
-- SPEC: Cột riêng: `user_id uuid NOT NULL` FK `users.id`; `token_hash char(64) NOT NULL UNIQUE`; `status token_status NOT NULL DEFAULT 'ACTIVE'`; `expires_at timestamptz NOT NULL`; `consumed_at timestamptz NULL`; `revoked_at timestamptz NULL`; `session_epoch bigint NOT NULL`; `request_ip_hash char(64) NULL`.
-- SPEC: Ràng buộc/chỉ mục/thời hạn lưu giữ: như `email_verification_tokens`; đặt lại thành công sẽ thu hồi mọi mã làm mới có thế hệ phiên cũ trong cùng giao dịch.
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    token_hash char(64) NOT NULL UNIQUE,
    status token_status NOT NULL DEFAULT 'ACTIVE',
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz NULL,
    revoked_at timestamptz NULL,
    session_epoch bigint NOT NULL,
    request_ip_hash char(64) NULL
);

-- TBL-IAM-006 — mfa_methods (source lines 142-149)
-- SPEC: Tập cột: `ENTITY`.
-- SPEC: Cột riêng: `user_id uuid NOT NULL` FK `users.id`; `type mfa_method_type NOT NULL`; `label varchar(80) NULL`; `secret_ciphertext bytea NULL`; `verified_at timestamptz NULL`; `disabled_at timestamptz NULL`.
-- SPEC: Ràng buộc: TOTP yêu cầu bí mật được mã hóa; mã khôi phục chỉ là phương thức thử thách dự phòng và hàm băm thực tế nằm ở `TBL-IAM-007`, không lưu mã gốc tại đây; duy nhất một phần trên `(user_id,type)` khi chưa bị vô hiệu hóa.
-- SPEC: Chỉ mục: `(user_id,disabled_at)`.
-- SPEC: Dữ liệu: SENSITIVE; chỉ xóa cứng sau khi tài khoản được ẩn danh hóa và hết thời gian tạm giữ pháp lý.
CREATE TABLE IF NOT EXISTS mfa_methods (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    row_version bigint NOT NULL DEFAULT 1,
    user_id uuid NOT NULL,
    type mfa_method_type NOT NULL,
    label varchar(80) NULL,
    secret_ciphertext bytea NULL,
    verified_at timestamptz NULL,
    disabled_at timestamptz NULL,
    CONSTRAINT ck_mfa_methods_row_version CHECK (row_version >= 1)
);

-- TBL-IAM-007 — mfa_recovery_codes (source lines 150-156)
-- SPEC: Tập cột: `IMMUTABLE`.
-- SPEC: Cột riêng: `method_id uuid NOT NULL` FK `mfa_methods.id`; `code_hash char(64) NOT NULL UNIQUE`; `consumed_at timestamptz NULL`; `batch_id uuid NOT NULL`.
-- SPEC: Ràng buộc: chỉ mã chưa dùng mới được dùng một lần; cập nhật duy nhất được phép là đặt `consumed_at` theo một chiều.
-- SPEC: Chỉ mục: `(method_id,consumed_at)`; SENSITIVE.
CREATE TABLE IF NOT EXISTS mfa_recovery_codes (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    method_id uuid NOT NULL,
    code_hash char(64) NOT NULL UNIQUE,
    consumed_at timestamptz NULL,
    batch_id uuid NOT NULL
);

-- TBL-IAM-008 — mfa_challenges (source lines 157-163)
-- SPEC: Tập cột: `ENTITY`.
-- SPEC: Cột riêng: `user_id uuid NOT NULL` FK `users.id`; `session_id uuid NULL`; `purpose varchar(32) NOT NULL`; `challenge_hash char(64) NOT NULL UNIQUE`; `expires_at timestamptz NOT NULL`; `attempt_count integer NOT NULL DEFAULT 0`; `max_attempts integer NOT NULL DEFAULT 5`; `verified_at timestamptz NULL`; `invalidated_at timestamptz NULL`.
-- SPEC: Ràng buộc: `expires_at>created_at`, `0<=attempt_count<=max_attempts`; hoàn tất theo một chiều.
-- SPEC: Chỉ mục: `(user_id,purpose,expires_at DESC)`; dọn sau 180 ngày.
CREATE TABLE IF NOT EXISTS mfa_challenges (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    row_version bigint NOT NULL DEFAULT 1,
    user_id uuid NOT NULL,
    session_id uuid NULL,
    purpose varchar(32) NOT NULL,
    challenge_hash char(64) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 5,
    verified_at timestamptz NULL,
    invalidated_at timestamptz NULL,
    CONSTRAINT ck_mfa_challenges_row_version CHECK (row_version >= 1),
    CONSTRAINT ck_mfa_challenges_e4dc85c8 CHECK (expires_at>created_at),
    CONSTRAINT ck_mfa_challenges_398bfc63 CHECK ((0 <= attempt_count AND attempt_count <= max_attempts))
);

-- TBL-IAM-009 — auth_sessions (source lines 164-171)
-- SPEC: Tập cột: `ENTITY`.
-- SPEC: Cột riêng: `user_id uuid NOT NULL` FK `users.id`; `status session_status NOT NULL DEFAULT 'ACTIVE'`; `session_epoch bigint NOT NULL`; `device_id_hash char(64) NULL`; `device_name varchar(120) NULL`; `ip_hash char(64) NULL`; `user_agent_hash char(64) NULL`; `last_seen_at timestamptz NOT NULL`; `expires_at timestamptz NOT NULL`; `revoked_at timestamptz NULL`; `revoke_reason varchar(100) NULL`.
-- SPEC: Ràng buộc: `expires_at>created_at`; trạng thái thu hồi/xâm phạm yêu cầu `revoked_at`; không lưu IP/tác nhân người dùng gốc.
-- SPEC: Chỉ mục: `(user_id,status,last_seen_at DESC)`; chỉ mục một phần trên `(expires_at)` khi `ACTIVE`.
-- SPEC: Thời hạn lưu giữ: 24 tháng cho điều tra bảo mật, sau đó xóa/băm sâu hơn theo quy định tạm giữ pháp lý.
CREATE TABLE IF NOT EXISTS auth_sessions (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    row_version bigint NOT NULL DEFAULT 1,
    user_id uuid NOT NULL,
    status session_status NOT NULL DEFAULT 'ACTIVE',
    session_epoch bigint NOT NULL,
    device_id_hash char(64) NULL,
    device_name varchar(120) NULL,
    ip_hash char(64) NULL,
    user_agent_hash char(64) NULL,
    last_seen_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz NULL,
    revoke_reason varchar(100) NULL,
    CONSTRAINT ck_auth_sessions_row_version CHECK (row_version >= 1),
    CONSTRAINT ck_auth_sessions_e4dc85c8 CHECK (expires_at>created_at)
);

-- TBL-IAM-010 — refresh_tokens (source lines 172-179)
-- SPEC: Tập cột: `IMMUTABLE`.
-- SPEC: Cột riêng: `session_id uuid NOT NULL` FK `auth_sessions.id`; `family_id uuid NOT NULL`; `parent_token_id uuid NULL` self-FK; `token_hash char(64) NOT NULL UNIQUE`; `status token_status NOT NULL DEFAULT 'ACTIVE'`; `issued_at timestamptz NOT NULL`; `expires_at timestamptz NOT NULL`; `rotated_to_id uuid NULL` self-FK; `consumed_at timestamptz NULL`; `reuse_detected_at timestamptz NULL`.
-- SPEC: Ràng buộc: một mã thông báo chỉ có một bản con; duy nhất một phần trên `parent_token_id` khi có giá trị; `expires_at>issued_at`; chuyển trạng thái một chiều bằng thủ tục. Khi phát hiện dùng lại, khóa cả họ mã thông báo và phiên trong cùng giao dịch.
-- SPEC: Chỉ mục: `(family_id,status)`; `(session_id,issued_at DESC)`; `(expires_at)`.
-- SPEC: Dữ liệu: chỉ lưu hàm băm mã thông báo; giữ 24 tháng sau khi hết hạn.
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    session_id uuid NOT NULL,
    family_id uuid NOT NULL,
    parent_token_id uuid NULL,
    token_hash char(64) NOT NULL UNIQUE,
    status token_status NOT NULL DEFAULT 'ACTIVE',
    issued_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    rotated_to_id uuid NULL,
    consumed_at timestamptz NULL,
    reuse_detected_at timestamptz NULL,
    CONSTRAINT ck_refresh_tokens_20499e92 CHECK (expires_at>issued_at)
);

-- TBL-IAM-011 — signing_keys (source lines 180-188)
-- SPEC: Tập cột: `ENTITY`.
-- SPEC: Cột riêng: `kid varchar(80) NOT NULL UNIQUE`; `algorithm varchar(16) NOT NULL DEFAULT 'ES256'`; `public_jwk jsonb NOT NULL`; `private_key_ref varchar(300) NOT NULL`; `not_before timestamptz NOT NULL`; `not_after timestamptz NOT NULL`; `activated_at timestamptz NULL`; `retired_at timestamptz NULL`.
-- SPEC: Ràng buộc: chỉ `ES256`; `not_after>not_before`; vật liệu khóa riêng chỉ là tham chiếu KMS/Vault.
-- SPEC: Chỉ mục: `(activated_at,retired_at)`; JWK công khai là INTERNAL, tham chiếu khóa là SENSITIVE.
CREATE TABLE IF NOT EXISTS signing_keys (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    row_version bigint NOT NULL DEFAULT 1,
    kid varchar(80) NOT NULL UNIQUE,
    algorithm varchar(16) NOT NULL DEFAULT 'ES256',
    public_jwk jsonb NOT NULL,
    private_key_ref varchar(300) NOT NULL,
    not_before timestamptz NOT NULL,
    not_after timestamptz NOT NULL,
    activated_at timestamptz NULL,
    retired_at timestamptz NULL,
    CONSTRAINT ck_signing_keys_row_version CHECK (row_version >= 1),
    CONSTRAINT ck_signing_keys_3131a65c CHECK (not_after>not_before)
);

-- TBL-IAM-012 — roles (source lines 189-195)
-- SPEC: Tập cột: `ENTITY`.
-- SPEC: Cột riêng: `code varchar(80) NOT NULL UNIQUE`; `name varchar(120) NOT NULL`; `description varchar(500) NOT NULL`; `is_privileged boolean NOT NULL DEFAULT false`; `is_system boolean NOT NULL DEFAULT true`; `disabled_at timestamptz NULL`.
-- SPEC: Ràng buộc: mã chữ hoa dạng `^[A-Z][A-Z0-9_]{1,79}$`; vai trò hệ thống không đổi mã hoặc xóa cứng.
-- SPEC: Chỉ mục: `(disabled_at,code)`.
CREATE TABLE IF NOT EXISTS roles (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    row_version bigint NOT NULL DEFAULT 1,
    code varchar(80) NOT NULL UNIQUE,
    name varchar(120) NOT NULL,
    description varchar(500) NOT NULL,
    is_privileged boolean NOT NULL DEFAULT false,
    is_system boolean NOT NULL DEFAULT true,
    disabled_at timestamptz NULL,
    CONSTRAINT ck_roles_row_version CHECK (row_version >= 1)
);

-- TBL-IAM-013 — permissions (source lines 196-202)
-- SPEC: Tập cột: `ENTITY`.
-- SPEC: Cột riêng: `code varchar(120) NOT NULL UNIQUE`; `service varchar(20) NOT NULL`; `description varchar(500) NOT NULL`; `risk_level smallint NOT NULL DEFAULT 1`.
-- SPEC: Ràng buộc: `service IN ('IDENTITY','STUDY','WORK')`; `risk_level BETWEEN 1 AND 5`.
-- SPEC: Chỉ mục: `(service,code)`.
CREATE TABLE IF NOT EXISTS permissions (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    row_version bigint NOT NULL DEFAULT 1,
    code varchar(120) NOT NULL UNIQUE,
    service varchar(20) NOT NULL,
    description varchar(500) NOT NULL,
    risk_level smallint NOT NULL DEFAULT 1,
    CONSTRAINT ck_permissions_row_version CHECK (row_version >= 1),
    CONSTRAINT ck_permissions_1c311d25 CHECK (risk_level BETWEEN 1 AND 5)
);

-- TBL-IAM-014 — role_permissions (source lines 203-209)
-- SPEC: Tập cột: `IMMUTABLE`.
-- SPEC: Cột riêng: `role_id uuid NOT NULL` FK `roles.id`; `permission_id uuid NOT NULL` FK `permissions.id`; `granted_by uuid NOT NULL` FK `users.id`; `revoked_at timestamptz NULL`; `revoked_by uuid NULL` FK `users.id`.
-- SPEC: Ràng buộc: duy nhất một phần trên `(role_id,permission_id)` khi `revoked_at IS NULL`; `revoked_by` là bắt buộc khi đã thu hồi.
-- SPEC: Chỉ mục: `(permission_id,revoked_at)`.
CREATE TABLE IF NOT EXISTS role_permissions (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    granted_by uuid NOT NULL,
    revoked_at timestamptz NULL,
    revoked_by uuid NULL
);

-- TBL-IAM-015 — user_role_assignments (source lines 210-218)
-- SPEC: Tập cột: `IMMUTABLE`.
-- SPEC: Cột riêng: `user_id uuid NOT NULL` FK `users.id`; `role_id uuid NOT NULL` FK `roles.id`; `scope_type varchar(24) NOT NULL DEFAULT 'PLATFORM'`; `scope_id uuid NULL`; `valid_from timestamptz NOT NULL DEFAULT now()`; `valid_until timestamptz NULL`; `granted_by uuid NOT NULL` FK `users.id`; `revoked_at timestamptz NULL`; `revoked_by uuid NULL` FK `users.id`; `reason varchar(500) NOT NULL`.
-- SPEC: Ràng buộc: `valid_until>valid_from` nếu có; phạm vi `PLATFORM` yêu cầu `scope_id` không có giá trị; duy nhất một phần trên `(user_id,role_id,scope_type,scope_id)` khi còn hiệu lực; việc gán vai trò đặc quyền yêu cầu MFA ở tầng dịch vụ.
-- SPEC: Chỉ mục: `(user_id,revoked_at,valid_until)`; `(scope_type,scope_id,revoked_at)`.
CREATE TABLE IF NOT EXISTS user_role_assignments (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    scope_type varchar(24) NOT NULL DEFAULT 'PLATFORM',
    scope_id uuid NULL,
    valid_from timestamptz NOT NULL DEFAULT now(),
    valid_until timestamptz NULL,
    granted_by uuid NOT NULL,
    revoked_at timestamptz NULL,
    revoked_by uuid NULL,
    reason varchar(500) NOT NULL,
    CONSTRAINT ck_user_role_assignments_149ff6b8 CHECK (valid_until>valid_from)
);

-- TBL-IAM-016 — idempotency_keys (source lines 219-225)
-- SPEC: Tập cột: `ENTITY`.
-- SPEC: Cột riêng: `actor_id uuid NULL`; `operation varchar(120) NOT NULL`; `key_hash char(64) NOT NULL`; `request_hash char(64) NOT NULL`; `response_status integer NULL`; `response_body jsonb NULL`; `locked_until timestamptz NULL`; `completed_at timestamptz NULL`; `expires_at timestamptz NOT NULL`.
-- SPEC: Ràng buộc: duy nhất `(actor_id,operation,key_hash)`; cùng khóa nhưng khác hàm băm yêu cầu trả xung đột; phản hồi phải được che dữ liệu.
-- SPEC: Chỉ mục: `(expires_at)`; dọn sau 24 giờ, riêng đăng ký giữ 7 ngày.
CREATE TABLE IF NOT EXISTS idempotency_keys (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    row_version bigint NOT NULL DEFAULT 1,
    actor_id uuid NULL,
    operation varchar(120) NOT NULL,
    key_hash char(64) NOT NULL,
    request_hash char(64) NOT NULL,
    response_status integer NULL,
    response_body jsonb NULL,
    locked_until timestamptz NULL,
    completed_at timestamptz NULL,
    expires_at timestamptz NOT NULL,
    CONSTRAINT ck_idempotency_keys_row_version CHECK (row_version >= 1)
);

-- TBL-IAM-017 — security_audit_events (source lines 226-233)
-- SPEC: Tập cột: `APPEND`.
-- SPEC: Cột riêng: `actor_id uuid NULL`; `subject_id uuid NULL`; `action varchar(120) NOT NULL`; `outcome audit_outcome NOT NULL`; `reason_code varchar(80) NULL`; `trace_id varchar(64) NOT NULL`; `session_id uuid NULL`; `ip_hash char(64) NULL`; `user_agent_hash char(64) NULL`; `metadata jsonb NOT NULL DEFAULT '{}'`; `prev_hash char(64) NULL`; `event_hash char(64) NOT NULL UNIQUE`; `legal_hold_until timestamptz NULL`.
-- SPEC: Ràng buộc: hàm băm sự kiện tính từ tải tin chuẩn và `prev_hash`; từ chối/thất bại yêu cầu mã lý do; siêu dữ liệu qua lược đồ/che dữ liệu.
-- SPEC: Chỉ mục: `(subject_id,occurred_at DESC)`; `(actor_id,occurred_at DESC)`; `(trace_id)`; BRIN `(occurred_at)`.
-- SPEC: Thời hạn lưu giữ: tối thiểu 24 tháng; chuỗi hàm băm phát hiện sửa đổi; không xóa dây chuyền.
CREATE TABLE IF NOT EXISTS security_audit_events (
    id uuid NOT NULL PRIMARY KEY,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    actor_id uuid NULL,
    subject_id uuid NULL,
    action varchar(120) NOT NULL,
    outcome audit_outcome NOT NULL,
    reason_code varchar(80) NULL,
    trace_id varchar(64) NOT NULL,
    session_id uuid NULL,
    ip_hash char(64) NULL,
    user_agent_hash char(64) NULL,
    metadata jsonb NOT NULL DEFAULT '{}',
    prev_hash char(64) NULL,
    event_hash char(64) NOT NULL UNIQUE,
    legal_hold_until timestamptz NULL
);

-- TBL-IAM-018 — outbox_events (source lines 234-241)
-- SPEC: Tập cột: `IMMUTABLE`.
-- SPEC: Cột riêng: `aggregate_type varchar(80) NOT NULL`; `aggregate_id uuid NOT NULL`; `event_type varchar(120) NOT NULL`; `event_version integer NOT NULL`; `payload jsonb NOT NULL`; `available_at timestamptz NOT NULL DEFAULT now()`; `dedupe_key varchar(180) NOT NULL UNIQUE`; `trace_id varchar(64) NOT NULL`.
-- SPEC: Ràng buộc: `event_version>=1`; tải tin không chứa thông tin xác thực/mã thông báo gốc; toàn bộ hàng chỉ được thêm mới và không chứa trạng thái giao nhận có thể sửa.
-- SPEC: Chỉ mục: `(available_at,id)`; `(aggregate_type,aggregate_id,created_at)`.
-- SPEC: Thời hạn lưu giữ: 24 tháng; trạng thái xuất bản được suy ra từ lần thử ở bảng kế tiếp.
CREATE TABLE IF NOT EXISTS outbox_events (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    aggregate_type varchar(80) NOT NULL,
    aggregate_id uuid NOT NULL,
    event_type varchar(120) NOT NULL,
    event_version integer NOT NULL,
    payload jsonb NOT NULL,
    available_at timestamptz NOT NULL DEFAULT now(),
    dedupe_key varchar(180) NOT NULL UNIQUE,
    trace_id varchar(64) NOT NULL,
    CONSTRAINT ck_outbox_events_c58b33c0 CHECK (event_version>=1)
);

-- TBL-IAM-019 — consumer_inbox (source lines 242-248)
-- SPEC: Tập cột: `IMMUTABLE`.
-- SPEC: Cột riêng: `consumer varchar(100) NOT NULL`; `event_id uuid NOT NULL`; `event_type varchar(120) NOT NULL`; `payload_hash char(64) NOT NULL`; `received_at timestamptz NOT NULL DEFAULT now()`; `processed_at timestamptz NULL`; `result_code varchar(80) NULL`; `trace_id varchar(64) NOT NULL`.
-- SPEC: Ràng buộc: duy nhất `(consumer,event_id)`; cùng sự kiện nhưng khác hàm băm tải tin là lỗi bảo mật.
-- SPEC: Chỉ mục: `(consumer,processed_at,received_at)`; giữ 24 tháng.
CREATE TABLE IF NOT EXISTS consumer_inbox (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    consumer varchar(100) NOT NULL,
    event_id uuid NOT NULL,
    event_type varchar(120) NOT NULL,
    payload_hash char(64) NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now(),
    processed_at timestamptz NULL,
    result_code varchar(80) NULL,
    trace_id varchar(64) NOT NULL
);

-- TBL-IAM-020 — outbox_delivery_attempts (source lines 249-259)
-- SPEC: Tập cột: `APPEND`.
-- SPEC: Cột riêng: `outbox_event_id uuid NOT NULL` FK `outbox_events.id`; `attempt_no integer NOT NULL`; `status outbox_status NOT NULL`; `worker_id varchar(120) NOT NULL`; `broker_message_id varchar(180) NULL`; `error_code varchar(80) NULL`; `next_retry_at timestamptz NULL`; `payload_hash char(64) NOT NULL`.
-- SPEC: Ràng buộc: duy nhất `(outbox_event_id,attempt_no)`; `attempt>=1`; `status` không dùng `PENDING`, sự kiện chưa có lần thử là đang chờ; `PUBLISHED` là trạng thái kết thúc; `DEAD_LETTER` chỉ xuất hiện sau chính sách thử lại.
-- SPEC: Chỉ mục: `(outbox_event_id,attempt_no DESC)`; `(status,next_retry_at,occurred_at)`; chỉ được thêm mới trong 24 tháng.
CREATE TABLE IF NOT EXISTS outbox_delivery_attempts (
    id uuid NOT NULL PRIMARY KEY,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    outbox_event_id uuid NOT NULL,
    attempt_no integer NOT NULL,
    status outbox_status NOT NULL,
    worker_id varchar(120) NOT NULL,
    broker_message_id varchar(180) NULL,
    error_code varchar(80) NULL,
    next_retry_at timestamptz NULL,
    payload_hash char(64) NOT NULL
);

-- Foreign keys (declared after tables to avoid creation-order cycles).
ALTER TABLE user_emails ADD CONSTRAINT fk_user_emails_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE password_credentials ADD CONSTRAINT fk_password_credentials_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE email_verification_tokens ADD CONSTRAINT fk_email_verification_tokens_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE email_verification_tokens ADD CONSTRAINT fk_email_verification_tokens_email_id FOREIGN KEY (email_id) REFERENCES user_emails(id) ON DELETE RESTRICT;
ALTER TABLE password_reset_tokens ADD CONSTRAINT fk_password_reset_tokens_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE mfa_methods ADD CONSTRAINT fk_mfa_methods_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE mfa_recovery_codes ADD CONSTRAINT fk_mfa_recovery_codes_method_id FOREIGN KEY (method_id) REFERENCES mfa_methods(id) ON DELETE RESTRICT;
ALTER TABLE mfa_challenges ADD CONSTRAINT fk_mfa_challenges_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE auth_sessions ADD CONSTRAINT fk_auth_sessions_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE refresh_tokens ADD CONSTRAINT fk_refresh_tokens_session_id FOREIGN KEY (session_id) REFERENCES auth_sessions(id) ON DELETE RESTRICT;
ALTER TABLE refresh_tokens ADD CONSTRAINT fk_refresh_tokens_parent_token_id FOREIGN KEY (parent_token_id) REFERENCES refresh_tokens(id) ON DELETE RESTRICT;
ALTER TABLE refresh_tokens ADD CONSTRAINT fk_refresh_tokens_rotated_to_id FOREIGN KEY (rotated_to_id) REFERENCES refresh_tokens(id) ON DELETE RESTRICT;
ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_role_id FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT;
ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_permission_id FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE RESTRICT;
ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_granted_by FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_revoked_by FOREIGN KEY (revoked_by) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE user_role_assignments ADD CONSTRAINT fk_user_role_assignments_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE user_role_assignments ADD CONSTRAINT fk_user_role_assignments_role_id FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT;
ALTER TABLE user_role_assignments ADD CONSTRAINT fk_user_role_assignments_granted_by FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE user_role_assignments ADD CONSTRAINT fk_user_role_assignments_revoked_by FOREIGN KEY (revoked_by) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE outbox_delivery_attempts ADD CONSTRAINT fk_outbox_delivery_attempts_outbox_event_id FOREIGN KEY (outbox_event_id) REFERENCES outbox_events(id) ON DELETE RESTRICT;

-- Unique constraints and indexes.
CREATE INDEX IF NOT EXISTS ix_users_status_created_at ON users (status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_users_deletion_requested_at ON users (deletion_requested_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_emails_user_id ON user_emails (user_id) WHERE is_primary=true AND replaced_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_emails_email_normalized ON user_emails (email_normalized) WHERE replaced_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_user_emails_user_id_replaced_at ON user_emails (user_id, replaced_at);
CREATE INDEX IF NOT EXISTS ix_email_verification_tokens_user_id_status_expires_at ON email_verification_tokens (user_id,status,expires_at DESC);
CREATE INDEX IF NOT EXISTS ix_mfa_methods_user_id_disabled_at ON mfa_methods (user_id,disabled_at);
CREATE INDEX IF NOT EXISTS ix_mfa_recovery_codes_method_id_consumed_at ON mfa_recovery_codes (method_id,consumed_at);
CREATE INDEX IF NOT EXISTS ix_mfa_challenges_user_id_purpose_expires_at ON mfa_challenges (user_id,purpose,expires_at DESC);
CREATE INDEX IF NOT EXISTS ix_auth_sessions_user_id_status_last_seen_at ON auth_sessions (user_id,status,last_seen_at DESC);
CREATE INDEX IF NOT EXISTS ix_auth_sessions_expires_at ON auth_sessions (expires_at);
CREATE INDEX IF NOT EXISTS ix_refresh_tokens_family_id_status ON refresh_tokens (family_id,status);
CREATE INDEX IF NOT EXISTS ix_refresh_tokens_session_id_issued_at ON refresh_tokens (session_id,issued_at DESC);
CREATE INDEX IF NOT EXISTS ix_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX IF NOT EXISTS ix_signing_keys_activated_at_retired_at ON signing_keys (activated_at,retired_at);
CREATE INDEX IF NOT EXISTS ix_roles_disabled_at_code ON roles (disabled_at,code);
CREATE INDEX IF NOT EXISTS ix_permissions_service_code ON permissions (service,code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_role_permissions_role_id_permission_id ON role_permissions (role_id, permission_id) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_role_permissions_permission_id_revoked_at ON role_permissions (permission_id,revoked_at);
CREATE INDEX IF NOT EXISTS ix_user_role_assignments_user_id_revoked_at_valid_until ON user_role_assignments (user_id,revoked_at,valid_until);
CREATE INDEX IF NOT EXISTS ix_user_role_assignments_scope_type_scope_id_revoked_at ON user_role_assignments (scope_type,scope_id,revoked_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_idempotency_keys_actor_id_operation_key_hash ON idempotency_keys (actor_id, operation, key_hash);
CREATE INDEX IF NOT EXISTS ix_idempotency_keys_expires_at ON idempotency_keys (expires_at);
CREATE INDEX IF NOT EXISTS ix_security_audit_events_subject_id_occurred_at ON security_audit_events (subject_id,occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_security_audit_events_actor_id_occurred_at ON security_audit_events (actor_id,occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_security_audit_events_trace_id ON security_audit_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_security_audit_events_occurred_at ON security_audit_events USING BRIN (occurred_at);
CREATE INDEX IF NOT EXISTS ix_outbox_events_available_at_id ON outbox_events (available_at,id);
CREATE INDEX IF NOT EXISTS ix_outbox_events_aggregate_type_aggregate_id_created_at ON outbox_events (aggregate_type,aggregate_id,created_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_consumer_inbox_consumer_event_id ON consumer_inbox (consumer, event_id);
CREATE INDEX IF NOT EXISTS ix_consumer_inbox_consumer_processed_at_received_at ON consumer_inbox (consumer,processed_at,received_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_outbox_delivery_attempts_outbox_event_id_attempt_no ON outbox_delivery_attempts (outbox_event_id, attempt_no);
CREATE INDEX IF NOT EXISTS ix_outbox_delivery_attempts_outbox_event_id_attempt_no ON outbox_delivery_attempts (outbox_event_id,attempt_no DESC);
CREATE INDEX IF NOT EXISTS ix_outbox_delivery_attempts_status_next_retry_at_occurred_at ON outbox_delivery_attempts (status,next_retry_at,occurred_at);

-- Standard lifecycle triggers from the mandatory column-set semantics.
DROP TRIGGER IF EXISTS trg_users_touch ON users;
CREATE TRIGGER trg_users_touch BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION s2w_touch_entity();
DROP TRIGGER IF EXISTS trg_user_emails_touch ON user_emails;
CREATE TRIGGER trg_user_emails_touch BEFORE UPDATE ON user_emails FOR EACH ROW EXECUTE FUNCTION s2w_touch_entity();
DROP TRIGGER IF EXISTS trg_password_credentials_touch ON password_credentials;
CREATE TRIGGER trg_password_credentials_touch BEFORE UPDATE ON password_credentials FOR EACH ROW EXECUTE FUNCTION s2w_touch_entity();
DROP TRIGGER IF EXISTS trg_email_verification_tokens_no_delete ON email_verification_tokens;
CREATE TRIGGER trg_email_verification_tokens_no_delete BEFORE DELETE ON email_verification_tokens FOR EACH ROW EXECUTE FUNCTION s2w_prevent_delete();
DROP TRIGGER IF EXISTS trg_password_reset_tokens_no_delete ON password_reset_tokens;
CREATE TRIGGER trg_password_reset_tokens_no_delete BEFORE DELETE ON password_reset_tokens FOR EACH ROW EXECUTE FUNCTION s2w_prevent_delete();
DROP TRIGGER IF EXISTS trg_mfa_methods_touch ON mfa_methods;
CREATE TRIGGER trg_mfa_methods_touch BEFORE UPDATE ON mfa_methods FOR EACH ROW EXECUTE FUNCTION s2w_touch_entity();
DROP TRIGGER IF EXISTS trg_mfa_recovery_codes_no_delete ON mfa_recovery_codes;
CREATE TRIGGER trg_mfa_recovery_codes_no_delete BEFORE DELETE ON mfa_recovery_codes FOR EACH ROW EXECUTE FUNCTION s2w_prevent_delete();
DROP TRIGGER IF EXISTS trg_mfa_challenges_touch ON mfa_challenges;
CREATE TRIGGER trg_mfa_challenges_touch BEFORE UPDATE ON mfa_challenges FOR EACH ROW EXECUTE FUNCTION s2w_touch_entity();
DROP TRIGGER IF EXISTS trg_auth_sessions_touch ON auth_sessions;
CREATE TRIGGER trg_auth_sessions_touch BEFORE UPDATE ON auth_sessions FOR EACH ROW EXECUTE FUNCTION s2w_touch_entity();
DROP TRIGGER IF EXISTS trg_refresh_tokens_no_delete ON refresh_tokens;
CREATE TRIGGER trg_refresh_tokens_no_delete BEFORE DELETE ON refresh_tokens FOR EACH ROW EXECUTE FUNCTION s2w_prevent_delete();
DROP TRIGGER IF EXISTS trg_signing_keys_touch ON signing_keys;
CREATE TRIGGER trg_signing_keys_touch BEFORE UPDATE ON signing_keys FOR EACH ROW EXECUTE FUNCTION s2w_touch_entity();
DROP TRIGGER IF EXISTS trg_roles_touch ON roles;
CREATE TRIGGER trg_roles_touch BEFORE UPDATE ON roles FOR EACH ROW EXECUTE FUNCTION s2w_touch_entity();
DROP TRIGGER IF EXISTS trg_permissions_touch ON permissions;
CREATE TRIGGER trg_permissions_touch BEFORE UPDATE ON permissions FOR EACH ROW EXECUTE FUNCTION s2w_touch_entity();
DROP TRIGGER IF EXISTS trg_role_permissions_no_delete ON role_permissions;
CREATE TRIGGER trg_role_permissions_no_delete BEFORE DELETE ON role_permissions FOR EACH ROW EXECUTE FUNCTION s2w_prevent_delete();
DROP TRIGGER IF EXISTS trg_user_role_assignments_no_delete ON user_role_assignments;
CREATE TRIGGER trg_user_role_assignments_no_delete BEFORE DELETE ON user_role_assignments FOR EACH ROW EXECUTE FUNCTION s2w_prevent_delete();
DROP TRIGGER IF EXISTS trg_idempotency_keys_touch ON idempotency_keys;
CREATE TRIGGER trg_idempotency_keys_touch BEFORE UPDATE ON idempotency_keys FOR EACH ROW EXECUTE FUNCTION s2w_touch_entity();
DROP TRIGGER IF EXISTS trg_security_audit_events_append_only ON security_audit_events;
CREATE TRIGGER trg_security_audit_events_append_only BEFORE UPDATE OR DELETE ON security_audit_events FOR EACH ROW EXECUTE FUNCTION s2w_prevent_update_delete();
DROP TRIGGER IF EXISTS trg_outbox_events_no_delete ON outbox_events;
CREATE TRIGGER trg_outbox_events_no_delete BEFORE DELETE ON outbox_events FOR EACH ROW EXECUTE FUNCTION s2w_prevent_delete();
DROP TRIGGER IF EXISTS trg_consumer_inbox_no_delete ON consumer_inbox;
CREATE TRIGGER trg_consumer_inbox_no_delete BEFORE DELETE ON consumer_inbox FOR EACH ROW EXECUTE FUNCTION s2w_prevent_delete();
DROP TRIGGER IF EXISTS trg_outbox_delivery_attempts_append_only ON outbox_delivery_attempts;
CREATE TRIGGER trg_outbox_delivery_attempts_append_only BEFORE UPDATE OR DELETE ON outbox_delivery_attempts FOR EACH ROW EXECUTE FUNCTION s2w_prevent_update_delete();

-- End of generated baseline.
-- Cross-row/state-machine/application-encryption rules that cannot be represented safely
-- by a local CHECK/FK/index remain documented above each table as SPEC comments.
