-- Study2Work Work — PostgreSQL schema bootstrap (design reference).
--
-- PostgreSQL 15+/Neon compatible. Prisma migrations are the runtime
-- source of truth; this file mirrors the clean Work domain schema for
-- review, bootstrap validation and database design documentation.
-- Authentication belongs to the external Identity service: no password,
-- access token or refresh token is stored here.
--
-- This file targets the existing public schema and intentionally contains
-- no CREATE DATABASE, seed data, trigger, stored procedure or grant.

SET search_path TO public;
SET TIME ZONE 'UTC';

CREATE TABLE "system_records" (
    "id" UUID NOT NULL,
    "key" VARCHAR(120) NOT NULL,
    "value" TEXT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_system_records_key" UNIQUE ("key")
);

CREATE TABLE "work_users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "identity_subject_id" VARCHAR(191) NOT NULL,
    "email" VARCHAR(320) NULL,
    "full_name" VARCHAR(150) NULL,
    "avatar_url" VARCHAR(2048) NULL,
    "bio" TEXT NULL,
    "phone" VARCHAR(32) NULL,
    "account_status" VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    "email_verified" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_work_users_identity_subject_id" UNIQUE ("identity_subject_id")
);

CREATE TABLE "tenants" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "tenant_type" VARCHAR(32) NOT NULL,
    "slug" VARCHAR(191) NOT NULL,
    "display_name" VARCHAR(200) NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "verification_status" VARCHAR(32) NOT NULL DEFAULT 'UNVERIFIED',
    "created_by_user_id" BIGINT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "deleted_at" TIMESTAMPTZ(6) NULL,
    CONSTRAINT "fk_tenants_created_by_user"
    FOREIGN KEY ("created_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "chk_tenants_type"
    CHECK ("tenant_type" IN ('ENTERPRISE', 'UNIVERSITY')),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_tenants_slug" UNIQUE ("slug")
);

CREATE TABLE "enterprise_profiles" (
    "tenant_id" BIGINT NOT NULL,
    "legal_name" VARCHAR(255) NOT NULL,
    "public_name" VARCHAR(255) NULL,
    "registration_number" VARCHAR(120) NULL,
    "description" TEXT NULL,
    "website_url" VARCHAR(2048) NULL,
    "contact_email" VARCHAR(320) NULL,
    "contact_phone" VARCHAR(32) NULL,
    "address_line" VARCHAR(255) NULL,
    "city" VARCHAR(120) NULL,
    "country_code" CHAR(2) NULL,
    "verified_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_enterprise_profiles_tenant"
    FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("tenant_id"),
    CONSTRAINT "uq_enterprise_profiles_registration_number" UNIQUE ("registration_number")
);

CREATE TABLE "university_profiles" (
    "tenant_id" BIGINT NOT NULL,
    "legal_name" VARCHAR(255) NOT NULL,
    "public_name" VARCHAR(255) NULL,
    "campus_code" VARCHAR(120) NULL,
    "description" TEXT NULL,
    "website_url" VARCHAR(2048) NULL,
    "contact_email" VARCHAR(320) NULL,
    "contact_phone" VARCHAR(32) NULL,
    "address_line" VARCHAR(255) NULL,
    "city" VARCHAR(120) NULL,
    "country_code" CHAR(2) NULL,
    "verified_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_university_profiles_tenant"
    FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("tenant_id"),
    CONSTRAINT "uq_university_profiles_campus_code" UNIQUE ("campus_code")
);

CREATE TABLE "tenant_memberships" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "tenant_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'INVITED',
    "membership_version" INTEGER NOT NULL DEFAULT 1,
    "permission_codes_json" JSONB NULL,
    "invited_by_user_id" BIGINT NULL,
    "invited_at" TIMESTAMPTZ(6) NULL,
    "accepted_at" TIMESTAMPTZ(6) NULL,
    "revoked_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_tenant_memberships_tenant"
    FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_tenant_memberships_user"
    FOREIGN KEY ("user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_tenant_memberships_invited_by_user"
    FOREIGN KEY ("invited_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "chk_tenant_memberships_version"
    CHECK ("membership_version" > 0),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_tenant_memberships_tenant_user" UNIQUE ("tenant_id", "user_id")
);

CREATE TABLE "membership_roles" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "membership_id" BIGINT NOT NULL,
    "role_code" VARCHAR(64) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_membership_roles_membership"
    FOREIGN KEY ("membership_id") REFERENCES "tenant_memberships" ("id")
    ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_membership_roles_membership_role" UNIQUE ("membership_id", "role_code")
);

CREATE TABLE "candidate_profiles" (
    "user_id" BIGINT NOT NULL,
    "headline" VARCHAR(255) NULL,
    "summary" TEXT NULL,
    "location_text" VARCHAR(255) NULL,
    "website_url" VARCHAR(2048) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_candidate_profiles_user"
    FOREIGN KEY ("user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("user_id")
);

CREATE TABLE "candidate_privacy" (
    "user_id" BIGINT NOT NULL,
    "searchable" BOOLEAN NOT NULL DEFAULT FALSE,
    "contact_visible" BOOLEAN NOT NULL DEFAULT FALSE,
    "cv_visible" BOOLEAN NOT NULL DEFAULT FALSE,
    "study_evidence_visible" BOOLEAN NOT NULL DEFAULT FALSE,
    "updated_by_user_id" BIGINT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_candidate_privacy_user"
    FOREIGN KEY ("user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_candidate_privacy_updated_by_user"
    FOREIGN KEY ("updated_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    PRIMARY KEY ("user_id")
);

CREATE TABLE "skills" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(160) NOT NULL,
    "slug" VARCHAR(191) NOT NULL,
    "taxonomy_code" VARCHAR(120) NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_skills_slug" UNIQUE ("slug")
);

CREATE TABLE "candidate_skills" (
    "candidate_user_id" BIGINT NOT NULL,
    "skill_id" BIGINT NOT NULL,
    "proficiency_level" VARCHAR(64) NULL,
    "years_experience" DECIMAL(5,2) NULL,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_candidate_skills_candidate"
    FOREIGN KEY ("candidate_user_id") REFERENCES "candidate_profiles" ("user_id")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "fk_candidate_skills_skill"
    FOREIGN KEY ("skill_id") REFERENCES "skills" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "chk_candidate_skills_years_experience"
    CHECK ("years_experience" IS NULL OR "years_experience" >= 0),
    PRIMARY KEY ("candidate_user_id", "skill_id")
);

CREATE TABLE "candidate_education" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "candidate_user_id" BIGINT NOT NULL,
    "institution_name" VARCHAR(255) NOT NULL,
    "degree" VARCHAR(160) NULL,
    "field_of_study" VARCHAR(160) NULL,
    "start_date" DATE NULL,
    "end_date" DATE NULL,
    "description" TEXT NULL,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_candidate_education_candidate"
    FOREIGN KEY ("candidate_user_id") REFERENCES "candidate_profiles" ("user_id")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "chk_candidate_education_dates"
    CHECK ("end_date" IS NULL OR "start_date" IS NULL OR "end_date" >= "start_date"),
    PRIMARY KEY ("id")
);

CREATE TABLE "candidate_experiences" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "candidate_user_id" BIGINT NOT NULL,
    "employer_name" VARCHAR(255) NOT NULL,
    "job_title" VARCHAR(200) NOT NULL,
    "description" TEXT NULL,
    "start_date" DATE NULL,
    "end_date" DATE NULL,
    "is_current" BOOLEAN NOT NULL DEFAULT FALSE,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_candidate_experiences_candidate"
    FOREIGN KEY ("candidate_user_id") REFERENCES "candidate_profiles" ("user_id")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "chk_candidate_experiences_dates"
    CHECK ("end_date" IS NULL OR "start_date" IS NULL OR "end_date" >= "start_date"),
    PRIMARY KEY ("id")
);

CREATE TABLE "search_consents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "candidate_user_id" BIGINT NOT NULL,
    "purpose" VARCHAR(120) NOT NULL,
    "consent_status" VARCHAR(32) NOT NULL,
    "consent_version" VARCHAR(64) NOT NULL,
    "visible_fields_json" JSONB NULL,
    "effective_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "expires_at" TIMESTAMPTZ(6) NULL,
    "withdrawn_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_search_consents_candidate"
    FOREIGN KEY ("candidate_user_id") REFERENCES "candidate_profiles" ("user_id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "chk_search_consents_dates"
    CHECK ("expires_at" IS NULL OR "expires_at" >= "effective_at"),
    PRIMARY KEY ("id")
);

CREATE TABLE "file_assets" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "owner_user_id" BIGINT NULL,
    "owner_tenant_id" BIGINT NULL,
    "storage_provider" VARCHAR(32) NOT NULL,
    "object_key" VARCHAR(700) NOT NULL,
    "original_name" VARCHAR(255) NOT NULL,
    "content_type" VARCHAR(160) NOT NULL,
    "size_bytes" BIGINT NOT NULL,
    "checksum_sha256" CHAR(64) NULL,
    "purpose" VARCHAR(64) NOT NULL,
    "clean_status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "visibility" VARCHAR(32) NOT NULL DEFAULT 'PRIVATE',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "deleted_at" TIMESTAMPTZ(6) NULL,
    CONSTRAINT "fk_file_assets_owner_user"
    FOREIGN KEY ("owner_user_id") REFERENCES "work_users" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "fk_file_assets_owner_tenant"
    FOREIGN KEY ("owner_tenant_id") REFERENCES "tenants" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "chk_file_assets_owner"
    CHECK ("owner_user_id" IS NOT NULL OR "owner_tenant_id" IS NOT NULL),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_file_assets_object_key" UNIQUE ("object_key")
);

CREATE TABLE "cvs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "candidate_user_id" BIGINT NOT NULL,
    "title" VARCHAR(200) NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    "is_default" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "deleted_at" TIMESTAMPTZ(6) NULL,
    CONSTRAINT "fk_cvs_candidate"
    FOREIGN KEY ("candidate_user_id") REFERENCES "candidate_profiles" ("user_id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("id")
);

CREATE TABLE "cv_revisions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cv_id" BIGINT NOT NULL,
    "revision_number" INTEGER NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    "content_json" JSONB NULL,
    "created_by_user_id" BIGINT NOT NULL,
    "published_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_cv_revisions_cv"
    FOREIGN KEY ("cv_id") REFERENCES "cvs" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_cv_revisions_created_by_user"
    FOREIGN KEY ("created_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "chk_cv_revisions_numbers"
    CHECK ("revision_number" > 0 AND "version" > 0),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_cv_revisions_cv_revision" UNIQUE ("cv_id", "revision_number")
);

CREATE TABLE "cv_revision_sections" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cv_revision_id" BIGINT NOT NULL,
    "section_type" VARCHAR(64) NOT NULL,
    "section_order" INTEGER NOT NULL DEFAULT 0,
    "payload_json" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_cv_revision_sections_revision"
    FOREIGN KEY ("cv_revision_id") REFERENCES "cv_revisions" ("id")
    ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_cv_revision_sections_order" UNIQUE ("cv_revision_id", "section_order")
);

CREATE TABLE "portfolio_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "candidate_user_id" BIGINT NOT NULL,
    "file_asset_id" BIGINT NULL,
    "title" VARCHAR(200) NOT NULL,
    "description" TEXT NULL,
    "item_type" VARCHAR(32) NOT NULL,
    "url" VARCHAR(2048) NULL,
    "visibility" VARCHAR(32) NOT NULL DEFAULT 'PRIVATE',
    "status" VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_portfolio_items_candidate"
    FOREIGN KEY ("candidate_user_id") REFERENCES "candidate_profiles" ("user_id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_portfolio_items_file_asset"
    FOREIGN KEY ("file_asset_id") REFERENCES "file_assets" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    PRIMARY KEY ("id")
);

CREATE TABLE "jobs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "tenant_id" BIGINT NOT NULL,
    "public_slug" VARCHAR(191) NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    "visibility" VARCHAR(32) NOT NULL DEFAULT 'PRIVATE',
    "published_revision_id" BIGINT NULL,
    "created_by_user_id" BIGINT NOT NULL,
    "published_at" TIMESTAMPTZ(6) NULL,
    "closed_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "deleted_at" TIMESTAMPTZ(6) NULL,
    CONSTRAINT "fk_jobs_tenant"
    FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_jobs_created_by_user"
    FOREIGN KEY ("created_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_jobs_public_slug" UNIQUE ("public_slug")
);

CREATE TABLE "job_revisions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "job_id" BIGINT NOT NULL,
    "revision_number" INTEGER NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    "title" VARCHAR(255) NOT NULL,
    "summary" TEXT NULL,
    "description" TEXT NULL,
    "employment_type" VARCHAR(64) NULL,
    "seniority" VARCHAR(64) NULL,
    "salary_min" DECIMAL(20,4) NULL,
    "salary_max" DECIMAL(20,4) NULL,
    "salary_currency" CHAR(3) NULL,
    "location_mode" VARCHAR(32) NULL,
    "application_deadline" TIMESTAMPTZ(6) NULL,
    "requirements_json" JSONB NULL,
    "benefits_json" JSONB NULL,
    "application_questions_json" JSONB NULL,
    "created_by_user_id" BIGINT NOT NULL,
    "published_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_job_revisions_job"
    FOREIGN KEY ("job_id") REFERENCES "jobs" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_job_revisions_created_by_user"
    FOREIGN KEY ("created_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "chk_job_revisions_numbers"
    CHECK ("revision_number" > 0 AND "version" > 0),
    CONSTRAINT "chk_job_revisions_salary"
    CHECK (
      ("salary_min" IS NULL OR "salary_min" >= 0)
      AND ("salary_max" IS NULL OR "salary_max" >= 0)
      AND (
        "salary_min" IS NULL OR "salary_max" IS NULL OR "salary_max" >= "salary_min"
      )
    ),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_job_revisions_job_revision" UNIQUE ("job_id", "revision_number")
);

CREATE TABLE "job_revision_skills" (
    "job_revision_id" BIGINT NOT NULL,
    "skill_id" BIGINT NOT NULL,
    "is_required" BOOLEAN NOT NULL DEFAULT FALSE,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "fk_job_revision_skills_revision"
    FOREIGN KEY ("job_revision_id") REFERENCES "job_revisions" ("id")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "fk_job_revision_skills_skill"
    FOREIGN KEY ("skill_id") REFERENCES "skills" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("job_revision_id", "skill_id")
);

CREATE TABLE "job_revision_locations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "job_revision_id" BIGINT NOT NULL,
    "country_code" CHAR(2) NULL,
    "region" VARCHAR(120) NULL,
    "city" VARCHAR(120) NULL,
    "address_line" VARCHAR(255) NULL,
    "remote_allowed" BOOLEAN NOT NULL DEFAULT FALSE,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "fk_job_revision_locations_revision"
    FOREIGN KEY ("job_revision_id") REFERENCES "job_revisions" ("id")
    ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY ("id")
);

CREATE TABLE "saved_jobs" (
    "candidate_user_id" BIGINT NOT NULL,
    "job_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_saved_jobs_candidate"
    FOREIGN KEY ("candidate_user_id") REFERENCES "candidate_profiles" ("user_id")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "fk_saved_jobs_job"
    FOREIGN KEY ("job_id") REFERENCES "jobs" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("candidate_user_id", "job_id")
);

CREATE TABLE "candidate_invitations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "tenant_id" BIGINT NOT NULL,
    "job_id" BIGINT NOT NULL,
    "candidate_user_id" BIGINT NOT NULL,
    "invited_by_user_id" BIGINT NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "message" TEXT NULL,
    "expires_at" TIMESTAMPTZ(6) NULL,
    "responded_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_candidate_invitations_tenant"
    FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_candidate_invitations_job"
    FOREIGN KEY ("job_id") REFERENCES "jobs" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_candidate_invitations_candidate"
    FOREIGN KEY ("candidate_user_id") REFERENCES "candidate_profiles" ("user_id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_candidate_invitations_invited_by_user"
    FOREIGN KEY ("invited_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "chk_candidate_invitations_expiry"
    CHECK ("expires_at" IS NULL OR "expires_at" >= "created_at"),
    PRIMARY KEY ("id")
);

CREATE TABLE "study_evidence_records" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "candidate_user_id" BIGINT NULL,
    "external_evidence_id" VARCHAR(191) NOT NULL,
    "source_event_id" UUID NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "payload_hash" CHAR(64) NOT NULL,
    "payload_json" JSONB NULL,
    "received_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "revoked_at" TIMESTAMPTZ(6) NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_study_evidence_candidate"
    FOREIGN KEY ("candidate_user_id") REFERENCES "candidate_profiles" ("user_id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_study_evidence_external_id" UNIQUE ("external_evidence_id"),
    CONSTRAINT "uq_study_evidence_source_event_id" UNIQUE ("source_event_id")
);

CREATE TABLE "applications" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "job_id" BIGINT NOT NULL,
    "candidate_user_id" BIGINT NOT NULL,
    "job_revision_id" BIGINT NOT NULL,
    "cv_id" BIGINT NOT NULL,
    "cv_revision_id" BIGINT NOT NULL,
    "invitation_id" BIGINT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED',
    "source" VARCHAR(64) NULL,
    "job_snapshot_json" JSONB NOT NULL,
    "cv_snapshot_json" JSONB NOT NULL,
    "answers_snapshot_json" JSONB NULL,
    "evidence_status" VARCHAR(32) NOT NULL DEFAULT 'UNAVAILABLE',
    "submitted_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "withdrawn_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_applications_job"
    FOREIGN KEY ("job_id") REFERENCES "jobs" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_applications_candidate"
    FOREIGN KEY ("candidate_user_id") REFERENCES "candidate_profiles" ("user_id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_applications_job_revision"
    FOREIGN KEY ("job_revision_id") REFERENCES "job_revisions" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_applications_cv"
    FOREIGN KEY ("cv_id") REFERENCES "cvs" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_applications_cv_revision"
    FOREIGN KEY ("cv_revision_id") REFERENCES "cv_revisions" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_applications_invitation"
    FOREIGN KEY ("invitation_id") REFERENCES "candidate_invitations" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_applications_job_candidate" UNIQUE ("job_id", "candidate_user_id")
);

CREATE TABLE "application_answers" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "application_id" BIGINT NOT NULL,
    "question_key" VARCHAR(120) NOT NULL,
    "answer_json" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_application_answers_application"
    FOREIGN KEY ("application_id") REFERENCES "applications" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_application_answers_question" UNIQUE ("application_id", "question_key")
);

CREATE TABLE "application_status_history" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "application_id" BIGINT NOT NULL,
    "from_status" VARCHAR(32) NULL,
    "to_status" VARCHAR(32) NOT NULL,
    "changed_by_user_id" BIGINT NOT NULL,
    "reason" TEXT NULL,
    "metadata_json" JSONB NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_application_status_history_application"
    FOREIGN KEY ("application_id") REFERENCES "applications" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_application_status_history_changed_by_user"
    FOREIGN KEY ("changed_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("id")
);

CREATE TABLE "application_assignments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "application_id" BIGINT NOT NULL,
    "recruiter_user_id" BIGINT NOT NULL,
    "assigned_by_user_id" BIGINT NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    "assigned_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "removed_at" TIMESTAMPTZ(6) NULL,
    CONSTRAINT "fk_application_assignments_application"
    FOREIGN KEY ("application_id") REFERENCES "applications" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_application_assignments_recruiter"
    FOREIGN KEY ("recruiter_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_application_assignments_assigned_by_user"
    FOREIGN KEY ("assigned_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_application_assignments_application_recruiter" UNIQUE ("application_id", "recruiter_user_id")
);

CREATE TABLE "application_evidence" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "application_id" BIGINT NOT NULL,
    "study_evidence_record_id" BIGINT NULL,
    "external_evidence_id" VARCHAR(191) NOT NULL,
    "evidence_type" VARCHAR(64) NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "payload_hash" CHAR(64) NULL,
    "consent_status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "metadata_json" JSONB NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_application_evidence_application"
    FOREIGN KEY ("application_id") REFERENCES "applications" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_application_evidence_study_record"
    FOREIGN KEY ("study_evidence_record_id") REFERENCES "study_evidence_records" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_application_evidence_application_external" UNIQUE ("application_id", "external_evidence_id")
);

CREATE TABLE "job_review_cases" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "job_id" BIGINT NOT NULL,
    "job_revision_id" BIGINT NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "opened_by_user_id" BIGINT NOT NULL,
    "resolved_by_user_id" BIGINT NULL,
    "decision" VARCHAR(64) NULL,
    "decision_reason" TEXT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_job_review_cases_job"
    FOREIGN KEY ("job_id") REFERENCES "jobs" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_job_review_cases_revision"
    FOREIGN KEY ("job_revision_id") REFERENCES "job_revisions" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_job_review_cases_opened_by_user"
    FOREIGN KEY ("opened_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_job_review_cases_resolved_by_user"
    FOREIGN KEY ("resolved_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    PRIMARY KEY ("id")
);

CREATE TABLE "job_review_decisions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "review_case_id" BIGINT NOT NULL,
    "actor_user_id" BIGINT NOT NULL,
    "decision" VARCHAR(64) NOT NULL,
    "reason" TEXT NULL,
    "metadata_json" JSONB NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_job_review_decisions_case"
    FOREIGN KEY ("review_case_id") REFERENCES "job_review_cases" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_job_review_decisions_actor_user"
    FOREIGN KEY ("actor_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("id")
);

CREATE TABLE "university_affiliation_invitations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "university_tenant_id" BIGINT NOT NULL,
    "candidate_user_id" BIGINT NOT NULL,
    "invited_by_user_id" BIGINT NOT NULL,
    "purpose" VARCHAR(255) NOT NULL,
    "scope_json" JSONB NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "expires_at" TIMESTAMPTZ(6) NULL,
    "responded_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_university_affiliation_invitations_tenant"
    FOREIGN KEY ("university_tenant_id") REFERENCES "tenants" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_university_affiliation_invitations_candidate"
    FOREIGN KEY ("candidate_user_id") REFERENCES "candidate_profiles" ("user_id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_university_affiliation_invitations_invited_by_user"
    FOREIGN KEY ("invited_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "chk_university_affiliation_invitations_expiry"
    CHECK ("expires_at" IS NULL OR "expires_at" >= "created_at"),
    PRIMARY KEY ("id")
);

CREATE TABLE "university_affiliations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "university_tenant_id" BIGINT NOT NULL,
    "candidate_user_id" BIGINT NOT NULL,
    "invitation_id" BIGINT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "consent_scope_json" JSONB NOT NULL,
    "consent_version" VARCHAR(64) NOT NULL,
    "starts_at" TIMESTAMPTZ(6) NULL,
    "ends_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_university_affiliations_tenant"
    FOREIGN KEY ("university_tenant_id") REFERENCES "tenants" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_university_affiliations_candidate"
    FOREIGN KEY ("candidate_user_id") REFERENCES "candidate_profiles" ("user_id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_university_affiliations_invitation"
    FOREIGN KEY ("invitation_id") REFERENCES "university_affiliation_invitations" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "chk_university_affiliations_dates"
    CHECK ("ends_at" IS NULL OR "starts_at" IS NULL OR "ends_at" >= "starts_at"),
    PRIMARY KEY ("id")
);

CREATE TABLE "tenant_partnerships" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "tenant_a_id" BIGINT NOT NULL,
    "tenant_b_id" BIGINT NOT NULL,
    "requested_by_user_id" BIGINT NOT NULL,
    "purpose" VARCHAR(255) NOT NULL,
    "scope_json" JSONB NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "starts_at" TIMESTAMPTZ(6) NULL,
    "ends_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_tenant_partnerships_tenant_a"
    FOREIGN KEY ("tenant_a_id") REFERENCES "tenants" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_tenant_partnerships_tenant_b"
    FOREIGN KEY ("tenant_b_id") REFERENCES "tenants" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_tenant_partnerships_requested_by_user"
    FOREIGN KEY ("requested_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "chk_tenant_partnerships_distinct_tenants"
    CHECK ("tenant_a_id" <> "tenant_b_id"),
    CONSTRAINT "chk_tenant_partnerships_dates"
    CHECK ("ends_at" IS NULL OR "starts_at" IS NULL OR "ends_at" >= "starts_at"),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_tenant_partnership_pair" UNIQUE ("tenant_a_id", "tenant_b_id")
);

CREATE TABLE "conversations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "application_id" BIGINT NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    "last_message_sequence" BIGINT NOT NULL DEFAULT 0,
    "closed_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_conversations_application"
    FOREIGN KEY ("application_id") REFERENCES "applications" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_conversations_application" UNIQUE ("application_id")
);

CREATE TABLE "conversation_participants" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "conversation_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "participant_role" VARCHAR(32) NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    "joined_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "removed_at" TIMESTAMPTZ(6) NULL,
    CONSTRAINT "fk_conversation_participants_conversation"
    FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_conversation_participants_user"
    FOREIGN KEY ("user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_conversation_participants_conversation_user" UNIQUE ("conversation_id", "user_id")
);

CREATE TABLE "messages" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "conversation_id" BIGINT NOT NULL,
    "sender_user_id" BIGINT NOT NULL,
    "client_message_id" VARCHAR(191) NOT NULL,
    "sequence_number" BIGINT NOT NULL,
    "body" TEXT NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'SENT',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "edited_at" TIMESTAMPTZ(6) NULL,
    "deleted_at" TIMESTAMPTZ(6) NULL,
    CONSTRAINT "fk_messages_conversation"
    FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_messages_sender_user"
    FOREIGN KEY ("sender_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_messages_conversation_client_id" UNIQUE ("conversation_id", "client_message_id"),
    CONSTRAINT "uq_messages_conversation_sequence" UNIQUE ("conversation_id", "sequence_number")
);

CREATE TABLE "interviews" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "application_id" BIGINT NOT NULL,
    "created_by_user_id" BIGINT NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'PROPOSED',
    "current_schedule_version" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "cancelled_at" TIMESTAMPTZ(6) NULL,
    CONSTRAINT "fk_interviews_application"
    FOREIGN KEY ("application_id") REFERENCES "applications" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_interviews_created_by_user"
    FOREIGN KEY ("created_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "chk_interviews_schedule_version"
    CHECK ("current_schedule_version" > 0),
    PRIMARY KEY ("id")
);

CREATE TABLE "interview_schedule_versions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "interview_id" BIGINT NOT NULL,
    "version_number" INTEGER NOT NULL,
    "starts_at_utc" TIMESTAMPTZ(6) NOT NULL,
    "ends_at_utc" TIMESTAMPTZ(6) NOT NULL,
    "timezone" VARCHAR(64) NOT NULL,
    "location_text" VARCHAR(255) NULL,
    "meeting_provider" VARCHAR(64) NULL,
    "meeting_reference" VARCHAR(255) NULL,
    "created_by_user_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_interview_schedule_versions_interview"
    FOREIGN KEY ("interview_id") REFERENCES "interviews" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_interview_schedule_versions_created_by_user"
    FOREIGN KEY ("created_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "chk_interview_schedule_versions_numbers"
    CHECK ("version_number" > 0),
    CONSTRAINT "chk_interview_schedule_versions_time"
    CHECK ("ends_at_utc" > "starts_at_utc"),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_interview_schedule_versions_interview_version" UNIQUE ("interview_id", "version_number")
);

CREATE TABLE "interview_participants" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "interview_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "participant_role" VARCHAR(32) NOT NULL,
    "response_status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "responded_at" TIMESTAMPTZ(6) NULL,
    CONSTRAINT "fk_interview_participants_interview"
    FOREIGN KEY ("interview_id") REFERENCES "interviews" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_interview_participants_user"
    FOREIGN KEY ("user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_interview_participants_interview_user" UNIQUE ("interview_id", "user_id")
);

CREATE TABLE "products" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "product_code" VARCHAR(120) NOT NULL,
    "product_type" VARCHAR(64) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT NULL,
    "amount" DECIMAL(20,4) NOT NULL,
    "currency" CHAR(3) NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    "metadata_json" JSONB NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "chk_products_amount"
    CHECK ("amount" >= 0),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_products_product_code" UNIQUE ("product_code")
);

CREATE TABLE "orders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "buyer_user_id" BIGINT NOT NULL,
    "tenant_id" BIGINT NULL,
    "external_order_reference" VARCHAR(191) NOT NULL,
    "payment_provider" VARCHAR(64) NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "subtotal_amount" DECIMAL(20,4) NOT NULL,
    "total_amount" DECIMAL(20,4) NOT NULL,
    "currency" CHAR(3) NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NULL,
    "settled_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_orders_buyer_user"
    FOREIGN KEY ("buyer_user_id") REFERENCES "work_users" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_orders_tenant"
    FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "chk_orders_amounts"
    CHECK ("subtotal_amount" >= 0 AND "total_amount" >= 0),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_orders_external_reference" UNIQUE ("external_order_reference")
);

CREATE TABLE "order_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "order_id" BIGINT NOT NULL,
    "product_id" BIGINT NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 1,
    "unit_amount" DECIMAL(20,4) NOT NULL,
    "line_amount" DECIMAL(20,4) NOT NULL,
    "metadata_json" JSONB NULL,
    CONSTRAINT "fk_order_items_order"
    FOREIGN KEY ("order_id") REFERENCES "orders" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_order_items_product"
    FOREIGN KEY ("product_id") REFERENCES "products" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "chk_order_items_amounts"
    CHECK ("quantity" > 0 AND "unit_amount" >= 0 AND "line_amount" >= 0),
    PRIMARY KEY ("id")
);

CREATE TABLE "payments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "order_id" BIGINT NOT NULL,
    "provider" VARCHAR(64) NOT NULL,
    "provider_payment_id" VARCHAR(191) NULL,
    "amount" DECIMAL(20,4) NOT NULL,
    "currency" CHAR(3) NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "transaction_code" VARCHAR(191) NULL,
    "provider_payload_json" JSONB NULL,
    "paid_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_payments_order"
    FOREIGN KEY ("order_id") REFERENCES "orders" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "chk_payments_amount"
    CHECK ("amount" >= 0),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_payments_provider_payment" UNIQUE ("provider", "provider_payment_id")
);

CREATE TABLE "entitlements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "owner_user_id" BIGINT NULL,
    "owner_tenant_id" BIGINT NULL,
    "product_id" BIGINT NULL,
    "source_order_id" BIGINT NULL,
    "entitlement_type" VARCHAR(64) NOT NULL,
    "quantity_remaining" DECIMAL(20,4) NOT NULL DEFAULT 0,
    "status" VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    "starts_at" TIMESTAMPTZ(6) NULL,
    "ends_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_entitlements_owner_user"
    FOREIGN KEY ("owner_user_id") REFERENCES "work_users" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "fk_entitlements_owner_tenant"
    FOREIGN KEY ("owner_tenant_id") REFERENCES "tenants" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "fk_entitlements_product"
    FOREIGN KEY ("product_id") REFERENCES "products" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "fk_entitlements_source_order"
    FOREIGN KEY ("source_order_id") REFERENCES "orders" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "chk_entitlements_owner"
    CHECK ("owner_user_id" IS NOT NULL OR "owner_tenant_id" IS NOT NULL),
    CONSTRAINT "chk_entitlements_quantity"
    CHECK ("quantity_remaining" >= 0),
    CONSTRAINT "chk_entitlements_dates"
    CHECK ("ends_at" IS NULL OR "starts_at" IS NULL OR "ends_at" >= "starts_at"),
    PRIMARY KEY ("id")
);

CREATE TABLE "credit_ledger" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "owner_user_id" BIGINT NULL,
    "owner_tenant_id" BIGINT NULL,
    "entitlement_id" BIGINT NULL,
    "delta_amount" DECIMAL(20,4) NOT NULL,
    "balance_after" DECIMAL(20,4) NOT NULL,
    "reason" VARCHAR(160) NOT NULL,
    "reference_type" VARCHAR(64) NULL,
    "reference_id" VARCHAR(191) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_credit_ledger_owner_user"
    FOREIGN KEY ("owner_user_id") REFERENCES "work_users" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "fk_credit_ledger_owner_tenant"
    FOREIGN KEY ("owner_tenant_id") REFERENCES "tenants" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "fk_credit_ledger_entitlement"
    FOREIGN KEY ("entitlement_id") REFERENCES "entitlements" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "chk_credit_ledger_owner"
    CHECK ("owner_user_id" IS NOT NULL OR "owner_tenant_id" IS NOT NULL),
    PRIMARY KEY ("id")
);

CREATE TABLE "promotions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "code" VARCHAR(120) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "discount_type" VARCHAR(32) NOT NULL,
    "discount_value" DECIMAL(20,4) NOT NULL,
    "starts_at" TIMESTAMPTZ(6) NULL,
    "ends_at" TIMESTAMPTZ(6) NULL,
    "max_uses" INTEGER NULL,
    "used_count" INTEGER NOT NULL DEFAULT 0,
    "status" VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "chk_promotions_discount"
    CHECK ("discount_value" >= 0),
    CONSTRAINT "chk_promotions_usage"
    CHECK ("max_uses" IS NULL OR "used_count" <= "max_uses"),
    CONSTRAINT "chk_promotions_dates"
    CHECK ("ends_at" IS NULL OR "starts_at" IS NULL OR "ends_at" >= "starts_at"),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_promotions_code" UNIQUE ("code")
);

CREATE TABLE "sponsored_job_slots" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "job_id" BIGINT NOT NULL,
    "order_id" BIGINT NULL,
    "promotion_id" BIGINT NULL,
    "placement" VARCHAR(64) NOT NULL,
    "starts_at" TIMESTAMPTZ(6) NOT NULL,
    "ends_at" TIMESTAMPTZ(6) NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "impressions_count" BIGINT NOT NULL DEFAULT 0,
    "clicks_count" BIGINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_sponsored_job_slots_job"
    FOREIGN KEY ("job_id") REFERENCES "jobs" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_sponsored_job_slots_order"
    FOREIGN KEY ("order_id") REFERENCES "orders" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "fk_sponsored_job_slots_promotion"
    FOREIGN KEY ("promotion_id") REFERENCES "promotions" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "chk_sponsored_job_slots_window"
    CHECK ("ends_at" > "starts_at"),
    PRIMARY KEY ("id")
);

CREATE TABLE "operations" (
    "id" UUID NOT NULL,
    "owner_user_id" BIGINT NULL,
    "kind" VARCHAR(64) NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    "result_json" JSONB NULL,
    "error_reason" VARCHAR(160) NULL,
    "error_message" TEXT NULL,
    "submitted_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "completed_at" TIMESTAMPTZ(6) NULL,
    CONSTRAINT "fk_operations_owner_user"
    FOREIGN KEY ("owner_user_id") REFERENCES "work_users" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    PRIMARY KEY ("id")
);

CREATE TABLE "idempotency_keys" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "scope_key" VARCHAR(255) NOT NULL,
    "endpoint" VARCHAR(255) NOT NULL,
    "idempotency_key" VARCHAR(191) NOT NULL,
    "request_hash" CHAR(64) NOT NULL,
    "response_status" SMALLINT NULL,
    "response_body_json" JSONB NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "expires_at" TIMESTAMPTZ(6) NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_idempotency_scope_endpoint_key" UNIQUE ("scope_key", "endpoint", "idempotency_key")
);

CREATE TABLE "audit_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "actor_user_id" BIGINT NULL,
    "tenant_id" BIGINT NULL,
    "action" VARCHAR(120) NOT NULL,
    "resource_type" VARCHAR(64) NOT NULL,
    "resource_id" BIGINT NULL,
    "reason" TEXT NULL,
    "metadata_json" JSONB NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_audit_events_actor_user"
    FOREIGN KEY ("actor_user_id") REFERENCES "work_users" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "fk_audit_events_tenant"
    FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    PRIMARY KEY ("id")
);

CREATE TABLE "tenant_risk_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "tenant_id" BIGINT NOT NULL,
    "event_type" VARCHAR(120) NOT NULL,
    "severity" VARCHAR(32) NOT NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    "details_json" JSONB NULL,
    "opened_by_user_id" BIGINT NULL,
    "resolved_by_user_id" BIGINT NULL,
    "resolved_at" TIMESTAMPTZ(6) NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT "fk_tenant_risk_events_tenant"
    FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "fk_tenant_risk_events_opened_by_user"
    FOREIGN KEY ("opened_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "fk_tenant_risk_events_resolved_by_user"
    FOREIGN KEY ("resolved_by_user_id") REFERENCES "work_users" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
    PRIMARY KEY ("id")
);

CREATE TABLE "webhook_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "provider" VARCHAR(64) NOT NULL,
    "provider_event_id" VARCHAR(191) NOT NULL,
    "event_type" VARCHAR(120) NOT NULL,
    "payload_hash" CHAR(64) NOT NULL,
    "payload_json" JSONB NULL,
    "status" VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
    "received_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    "processed_at" TIMESTAMPTZ(6) NULL,
    "error_message" TEXT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_webhook_events_provider_event" UNIQUE ("provider", "provider_event_id")
);

ALTER TABLE "jobs"
  ADD CONSTRAINT "fk_jobs_published_revision"
    FOREIGN KEY ("published_revision_id") REFERENCES "job_revisions" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

CREATE INDEX "ix_work_users_account_status" ON "work_users" ("account_status");
CREATE INDEX "ix_work_users_email" ON "work_users" ("email");
CREATE INDEX "ix_tenants_type_status" ON "tenants" ("tenant_type", "status");
CREATE INDEX "ix_tenant_memberships_user_status" ON "tenant_memberships" ("user_id", "status");
CREATE INDEX "ix_skills_taxonomy_code" ON "skills" ("taxonomy_code");
CREATE INDEX "ix_candidate_skills_skill" ON "candidate_skills" ("skill_id");
CREATE INDEX "ix_candidate_education_candidate_order" ON "candidate_education" ("candidate_user_id", "display_order");
CREATE INDEX "ix_candidate_experiences_candidate_order" ON "candidate_experiences" ("candidate_user_id", "display_order");
CREATE INDEX "ix_search_consents_candidate_status" ON "search_consents" ("candidate_user_id", "consent_status");
CREATE INDEX "ix_file_assets_user_status" ON "file_assets" ("owner_user_id", "clean_status");
CREATE INDEX "ix_file_assets_tenant_status" ON "file_assets" ("owner_tenant_id", "clean_status");
CREATE INDEX "ix_cvs_candidate_status" ON "cvs" ("candidate_user_id", "status");
CREATE INDEX "ix_cv_revisions_status" ON "cv_revisions" ("cv_id", "status");
CREATE INDEX "ix_cv_revision_sections_type" ON "cv_revision_sections" ("cv_revision_id", "section_type");
CREATE INDEX "ix_portfolio_items_candidate_visibility" ON "portfolio_items" ("candidate_user_id", "visibility", "status");
CREATE INDEX "ix_jobs_tenant_status" ON "jobs" ("tenant_id", "status");
CREATE INDEX "ix_jobs_public_listing" ON "jobs" ("status", "visibility", "published_at");
CREATE INDEX "ix_job_revisions_job_status" ON "job_revisions" ("job_id", "status");
CREATE INDEX "ix_job_revision_skills_skill" ON "job_revision_skills" ("skill_id");
CREATE INDEX "ix_job_revision_locations_revision_order" ON "job_revision_locations" ("job_revision_id", "display_order");
CREATE INDEX "ix_job_revision_locations_city" ON "job_revision_locations" ("city");
CREATE INDEX "ix_saved_jobs_job" ON "saved_jobs" ("job_id");
CREATE INDEX "ix_candidate_invitations_candidate_status" ON "candidate_invitations" ("candidate_user_id", "status");
CREATE INDEX "ix_candidate_invitations_job_status" ON "candidate_invitations" ("job_id", "status");
CREATE INDEX "ix_study_evidence_candidate_status" ON "study_evidence_records" ("candidate_user_id", "status");
CREATE INDEX "ix_applications_candidate_status" ON "applications" ("candidate_user_id", "status");
CREATE INDEX "ix_applications_job_status" ON "applications" ("job_id", "status");
CREATE INDEX "ix_applications_invitation" ON "applications" ("invitation_id");
CREATE INDEX "ix_application_status_history_application_time" ON "application_status_history" ("application_id", "created_at");
CREATE INDEX "ix_application_assignments_recruiter_status" ON "application_assignments" ("recruiter_user_id", "status");
CREATE INDEX "ix_application_evidence_application_status" ON "application_evidence" ("application_id", "status");
CREATE INDEX "ix_job_review_cases_job_status" ON "job_review_cases" ("job_id", "status");
CREATE INDEX "ix_job_review_cases_revision" ON "job_review_cases" ("job_revision_id");
CREATE INDEX "ix_job_review_decisions_case_time" ON "job_review_decisions" ("review_case_id", "created_at");
CREATE INDEX "ix_university_affiliation_invitations_candidate_status" ON "university_affiliation_invitations" ("candidate_user_id", "status");
CREATE INDEX "ix_university_affiliation_invitations_tenant_status" ON "university_affiliation_invitations" ("university_tenant_id", "status");
CREATE INDEX "ix_university_affiliations_candidate_status" ON "university_affiliations" ("candidate_user_id", "status");
CREATE INDEX "ix_university_affiliations_tenant_status" ON "university_affiliations" ("university_tenant_id", "status");
CREATE INDEX "ix_tenant_partnerships_status" ON "tenant_partnerships" ("status");
CREATE INDEX "ix_conversation_participants_user_status" ON "conversation_participants" ("user_id", "status");
CREATE INDEX "ix_messages_conversation_time" ON "messages" ("conversation_id", "created_at");
CREATE INDEX "ix_interviews_application_status" ON "interviews" ("application_id", "status");
CREATE INDEX "ix_interview_schedule_versions_time" ON "interview_schedule_versions" ("starts_at_utc", "ends_at_utc");
CREATE INDEX "ix_products_type_active" ON "products" ("product_type", "is_active");
CREATE INDEX "ix_orders_buyer_status" ON "orders" ("buyer_user_id", "status");
CREATE INDEX "ix_orders_tenant_status" ON "orders" ("tenant_id", "status");
CREATE INDEX "ix_order_items_order" ON "order_items" ("order_id");
CREATE INDEX "ix_payments_order_status" ON "payments" ("order_id", "status");
CREATE INDEX "ix_entitlements_user_status" ON "entitlements" ("owner_user_id", "status");
CREATE INDEX "ix_entitlements_tenant_status" ON "entitlements" ("owner_tenant_id", "status");
CREATE INDEX "ix_credit_ledger_user_time" ON "credit_ledger" ("owner_user_id", "created_at");
CREATE INDEX "ix_credit_ledger_tenant_time" ON "credit_ledger" ("owner_tenant_id", "created_at");
CREATE INDEX "ix_promotions_status_window" ON "promotions" ("status", "starts_at", "ends_at");
CREATE INDEX "ix_sponsored_job_slots_job_window" ON "sponsored_job_slots" ("job_id", "status", "starts_at", "ends_at");
CREATE INDEX "ix_operations_owner_status" ON "operations" ("owner_user_id", "status");
CREATE INDEX "ix_operations_status_updated" ON "operations" ("status", "updated_at");
CREATE INDEX "ix_idempotency_keys_expiry" ON "idempotency_keys" ("expires_at");
CREATE INDEX "ix_audit_events_tenant_time" ON "audit_events" ("tenant_id", "created_at");
CREATE INDEX "ix_audit_events_actor_time" ON "audit_events" ("actor_user_id", "created_at");
CREATE INDEX "ix_audit_events_resource_time" ON "audit_events" ("resource_type", "resource_id", "created_at");
CREATE INDEX "ix_tenant_risk_events_tenant_status" ON "tenant_risk_events" ("tenant_id", "status");
CREATE INDEX "ix_tenant_risk_events_severity_status" ON "tenant_risk_events" ("severity", "status");
CREATE INDEX "ix_webhook_events_status_received" ON "webhook_events" ("status", "received_at");
