name: learn2earn
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.1
  intl: ^0.19.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.jpg"

flutter:
  assets:
    - assets/
    - assets/bg_trangchu.jpg

  uses-material-design: true
