@startuml
title STUDY2WORK - Activity - Tim kiem ung vien

start

partition "Doanh nghiep" {
  :Mo chuc nang tim ung vien;
  :Nhap tu khoa;
  :Chon loc theo ky nang / kinh nghiem / dia diem;
  :Bat dau tim kiem;
}

partition "He thong" {
  :Phan tich bo loc;
  :Truy van danh sach ung vien;
  :Xep hang ket qua phu hop;
  :Hien thi danh sach ung vien;
}

partition "Doanh nghiep" {
  :Xem chi tiet ho so;
  :Luu ung vien vao shortlist;
  :Gui tin nhan / moi phong van neu can;
}

partition "He thong" {
  :Luu hanh dong cua nha tuyen dung;
  :Cap nhat lich su tuong tac;
}

stop
@enduml
